version: '3.9'

networks:
  zendata:
    driver: bridge

services:
  api:
    build: ./
    env_file:
      - .env
    ports:
      - 8094:8094
    networks:
      - zendata
    depends_on:
      - celery_worker
    volumes:
      - ./:/app

  celery_worker:
    build: 
      context: ./
      dockerfile: Dockerfile.celery
    env_file:
      - .env
    networks:
      - zendata
    depends_on:
      - rabbitmq
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rabbitmq:
    image: rabbitmq:latest
    networks:
      - zendata